courses/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
  path('', views.courses_index, name='courses_index'), 

  path('department', views.api_department_index, name='api_department_index'), 
  path('department/<int:id>', views.api_department_show, name='api_department_show'),
  path('course/<int:id>', views.api_course_show, name='api_course_show'),

  path('solve/', views.solve, name='solve'), 
  path('fill/', views.fill, name='fill'), 
  path('reset/', views.reset, name='reset'), 
  path('convert/', views.convert, name='convert'),
]

myschedule/urls.py
from django.contrib import admin
from django.urls import path, include

from courses.views import home_index

urlpatterns = [
    path('', home_index, name='home_index'),
    path('courses/', include('courses.urls')),
    path('admin/', admin.site.urls),
]

courses/models.py
from django.db import models

from itertools import product

class Department(models.Model):
  name = models.CharField(
    max_length=2,
    unique=True
  )

  def __str__(self):
    return self.name

class Course(models.Model):
  course_code = models.CharField(max_length=10, unique=True)
  course_name = models.CharField(max_length=40)
  sks = models.IntegerField(blank=True, null=True)
  term = models.IntegerField(blank=True, null=True)
  curriculum = models.CharField(max_length=16, blank=True)
  
  prerequisites = models.ManyToManyField(
    'self', symmetrical=False
  )
  departments = models.ManyToManyField(
    'Department', related_name='courses'
  )

  def __str__(self):
    return '{}:{}:{}'.format(self.course_code, ','.join(map(lambda d: d.name, self.departments.all())), self.course_name)

class CourseClass(models.Model):
  class Meta:
    unique_together = ('name', 'course', )

  name = models.CharField(max_length=40)
  LANGUAGE_CHOICES = (
    ('IDN', 'Indonesian'),
    ('ENG', 'English'),
  )
  language = models.CharField(
    max_length=3,
    choices=LANGUAGE_CHOICES, 
    blank=True
  )

  lecturers = models.ManyToManyField('Lecturer')
  course = models.ForeignKey(
    'Course', on_delete=models.CASCADE, related_name='course_classes', 
    blank=True, null=True
  )

  def clash_with(self, other):
    g = product(self.meetings.all(), other.meetings.all())
    try:
      while(True):
        meeting1, meeting2 = next(g)
        if meeting1.clash_with(meeting2):
          return True
    except StopIteration:
      pass
    return False

  def __str__(self):
    return self.name

class Lecturer(models.Model):
  name = models.CharField(max_length=60, unique=True)

  def __str__(self):
    return self.name

class Meeting(models.Model):
  DAY_CHOICES = (
    ('MON', 'Monday'),
    ('TUE', 'Tuesday'),
    ('WED', 'Wednesday'),
    ('THU', 'Thursday'),
    ('FRI', 'Friday'),
    ('SAT', 'Saturday'),
  )
  day = models.CharField(
    max_length=3, 
    choices=DAY_CHOICES, 
    blank=True
  )
  start_time = models.TimeField(auto_now=False, auto_now_add=False)
  end_time = models.TimeField(auto_now=False, auto_now_add=False)
  class_room = models.CharField(max_length=15)

  course_class = models.ForeignKey(
    'CourseClass', on_delete=models.CASCADE, 
    related_name='meetings', blank=True, null=True
  )

  def clash_with(self, other):
    if self.day == other.day and self._time_overlap(other):
      return True
    else:
      return False
    
  def _time_overlap(self, other):
    if self.start_time == other.start_time:
      return True
    if self.start_time < other.start_time:
      return False if self.end_time < other.start_time else True
    else:
      return other._time_overlap(self)
  
  def __str__(self):
    return '{}:{}-{}:{}'.format(self.day, self.start_time.strftime('%H.%M'), self.end_time.strftime('%H.%M'), self.class_room)

courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect, JsonResponse
from django.views.decorators.http import require_http_methods
from rest_framework.renderers import JSONRenderer

from .models import *
from .serializer import *
from . import utils
from json import loads

from .backtracking import Backtracking, FitnessFunction

@require_http_methods((["GET"]))
def home_index(request):
  return render(request, 'home/index.html')

@require_http_methods((["GET"]))
def courses_index(request):
  context = loads(api_department_index(request).content)
  return render(request, 'course/index.html', context)

@require_http_methods((["GET"]))
def api_department_index(request):
  json = {'data': []}
  for dep in Department.objects.all():
    serializer = DepartmentSerializer(dep)
    json['data'].append(serializer.data)
  return JsonResponse(json, json_dumps_params={'indent': 2})

@require_http_methods((["GET"]))
def api_department_show(request, id):
  json = {}
  serializer = DepartmentSerializer(get_object_or_404(Department, pk=id))
  json['data'] = serializer.data
  return JsonResponse(json, json_dumps_params={'indent': 2})

@require_http_methods((["GET"]))
def api_course_show(request, id):
  json = {}
  serializer = CourseSerializer(get_object_or_404(Course, pk=id))
  json['data'] = serializer.data
  return JsonResponse(json, json_dumps_params={'indent': 2})

@require_http_methods((["POST"]))
def solve(request):
  if request.method == 'POST':
    request_body_dict = loads(request.body.decode("utf-8"))
    json = {'data': {'selected': request_body_dict['check']}}
    json['data']['time_preference'] = request_body_dict['time_preference']
    json['data']['density_preference'] = request_body_dict['density_preference']
    bt = Backtracking()
    for course_id in json['data']['selected']:
      course_obj = Course.objects.get(id=course_id)
      bt.add_variable(course_obj, list(course_obj.course_classes.all()))
    bt.add_binary_constraint_to_all(lambda a, b: not a.clash_with(b))

    fitness_functions_used = []
    if request_body_dict['time_preference'] == 'morning':
      fitness_functions_used.append(FitnessFunction.PREFER_MORNING_CLASS)
    elif request_body_dict['time_preference'] == 'evening':
      fitness_functions_used.append(FitnessFunction.PREFER_EVENING_CLASS)

    if request_body_dict['density_preference'] == 'packed':
      fitness_functions_used.append(FitnessFunction.PREFER_PACKED_SCHEDULE)
    elif request_body_dict['density_preference'] == 'spread':
      fitness_functions_used.append(FitnessFunction.PREFER_SPREAD_SCHEDULE)

    result_obj = bt.get_solution(fitness_functions_used)
    result_list = []
    if result_obj:
      json['data']['solution_found'] = True
      for course, class_ in result_obj.items():
        result_list.append({'course':SimpleCourseSerializer(course).data, 'class': CourseClassSerializer(class_).data})
    else:
      json['data']['solution_found'] = False
    json['data']['result'] = result_list
    return JsonResponse(json, json_dumps_params={'indent': 2})

def fill(request):
  if request.user.is_superuser:
    return HttpResponse(utils.fill_all_course_data_to_db())
  else:
    return HttpResponseForbidden()
  
def reset(request):
  if request.user.is_superuser:
    return HttpResponse(utils.reset_db())
  else:
    return HttpResponseForbidden()

def convert(request):
  if request.user.is_superuser:
    return HttpResponse(utils.SiakParser.convert_all_html_to_json())
  else:
    return HttpResponseForbidden()

templates/_base.html
{% load static %}
<!doctype html> 
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'dist/style.css' %}" rel="stylesheet">
        {% block css %}{% endblock %}
    </head>
    <body>
        {% include '_navbar.html' %}
        {% block content %}{% endblock %}
        <script src="{% static 'dist/script.js' %}"></script> 
        {% block js %}{% endblock %}
    </body>
</html>

templates/_navbar.html
{% load static %}
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            <span class="title is-4">MySchedule</span>
        </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-end">
            <div class="navbar-item">
                <a href="https://gitlab.com/myschedule/myschedule" target="_blank">
                    <img src="{% static 'img/gitlab-logo.png' %}">
                    source code
                </a>
            </div>
        </div>
    </div>
</nav>

templates/course/index.html
{% extends '_base.html' %}
{% load static %}

{% block title %}MySchedule | Courses{% endblock %}

{% block content %}
<div class="container">
  <section class="section">
    <div class="columns">
      <div class="column is-10">
        <div id='calendar-container'>
          <div id='calendar'></div>
        </div>
      </div>
      <div class="column is-2">
        <section>
          <h2 class="title is-5">selected classes</h2>
          <div class="selected-classes">
          </div>
        </section>
      </div>
    </div>
  </section>
  <section class="section">
    <form action="{% url 'courses:solve' %}" id="course-form" method="post">
      {% csrf_token %}
      <div class="columns">
        <div class="column is-9">
          <h2 class="title">Select courses</h2>
          <div class="tabs">
            <ul style="justify-content: space-between;">
              <div style="display: flex;">
                {% for department in data %}
                <li><a class="title is-5">{{ department.name }}</a></li>
                {% endfor %}
              </div>
              <div class="button" id="unselect-all">unselect all</div>
            </ul>
          </div>
        </div>
      </div>
      <div class="columns">
        <div class="column is-9">
          <div class="tabs-content">
            {% for department in data %}
            <div class="tab-selection">
              {% for course in department.courses %}
              <div class="card">
                <input type="checkbox" data-course-code="{{ course.course_code }}" data-course-name="{{ course.course_name }}" 
                    value="{{ course.id }}" name="check">
                <label for="{{ course.course_code }}">
                  <div class="card-content" style="display: inline-block;">
                    <p class="title is-5">
                      {{ course.course_code }} {{ course.course_name }}
                    </p>
                    <p class="subtitle is-5">
                      {{ course.term }} term<br>
                      {{ course.sks }} credits
                      {% if course.prerequisites %}
                      <br>prerequisites<br>
                      {% for pre in course.prerequisites %}
                      {% if forloop.first == False %}, {% endif %}{{ pre.course_code }} {{ pre.course_name }}
                      {% endfor %}
                      {% endif %}
                    </p>
                  </div>
                </label>
              </div>
              {% endfor %}
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="column is-3">
          <div class="field">
            <button class="button is-large is-fullwidth" type="submit" id="course-form-submit">Submit</button>
          </div>
          <div class="field">
            <label for="time_preference">Time of class preference</label>
            <div class="control">
              <div class="select">
                <select name="time_preference" id="time_preference" style="overflow: hidden;">
                  <option value="morning">prefer morning class</option>
                  <option value="default" selected>no preference</option>
                  <option value="evening">prefer evening class</option>
                </select>
              </div>
            </div>
          </div>
          <div class="field">
            <label for="density_preference">Density of schedule preference</label>
            <div class="control">
              <div class="select">
                <select name="density_preference" id="density_preference" style="overflow: hidden;">
                  <option value="packed">prefer packed schedule</option>
                  <option value="default" selected>no preference</option>
                  <option value="spread">prefer spread schedule</option>
                </select>
              </div>
            </div>
          </div>
          <div>
            <h2 class="title is-5"><span id="selected-course-count">0</span> course(s) selected</h2>
            <div class="selected-courses">
            </div>
          </div>
        </div>
      </div>
    </form>
  </section>
  <div class="modal" id="success">
    <div class="modal-card">
      <header class="modal-card-head">
        <button class="delete" aria-label="close"></button>
      </header>
      <section class="modal-card-body">
        schedule found! check it out
      </section>
    </div>
  </div>
  <div class="modal" id="fail">
    <div class="modal-card">
      <header class="modal-card-head">
        <button class="delete" aria-label="close"></button>
      </header>
      <section class="modal-card-body">
        no possible schedule found
      </section>
    </div>
  </div>
</div>
<div class="alerts">
</div>

{% endblock %}

templates/home/index.html
{% extends '_base.html' %}
{% load static %}

{% block title %}MySchedule{% endblock %}

{% block content %}
<section class="hero is-fullheight">
  <div class="hero-body">
    <div class="container">
      <!-- <div class="is-flex" style="flex-direction: row; align-items: center;"> -->
      <div class="columns">
        <div class="column is-5">
          <div class="landing-image">
              <img src="{% static 'img/undraw_calendar_dutt.svg' %}" width="300px">
          </div>
        </div>
        <div class="column is-7">
            <div class="landing-text">
                <h1 class="title">
                  MySchedule
                </h1>
                <h2 class="subtitle">
                    <a href="{% url 'courses:courses_index' %}">start arranging your schedule now</a>
                </h2>
              </div>
        </div>
      </div>
        
        
      <!-- </div> -->
    </div>
  </div>
</section>
{% endblock %}